### ISSUE TITLE
tiny issue and suggetion

### ISSUE THREAD

**Issue by Infernogd** [Alphalaneous/Settings-Everywhere#1]
the settings button is overlapping one of the buttons of your other mod the integrated loquibot. My suggestion is to put the button where I put in in the second image, and lastly have a option to disable the setting button on the pause menu. Thanks :)
![image](https://github.com/user-attachments/assets/ffdcdcb0-51a8-4d8e-99d5-783c15ea1ab0)
![image](https://github.com/user-attachments/assets/fd6f31a0-fd26-4741-babd-3e26ec1b25ff)

**Comment by InfernoZv** [comment]
thanks for fixing :)
